In [887]:
import kagglehub
import pandas as pd

In [888]:
path = kagglehub.dataset_download('jasminemohamed2545/berber-english-160k-parallel-sentences-for-nlp')
print(path)

C:\Users\lassa\.cache\kagglehub\datasets\jasminemohamed2545\berber-english-160k-parallel-sentences-for-nlp\versions\1

In [889]:
df = pd.read_table('ber.txt')
df

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
0,Hi.,Azul.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1,Hi.,Azul fell-ak.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2,Hi.,Azul fell-am.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3,Hi.,Azul fell-awen.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Azul fell-awent.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
...,...,...,...
160877,"One of my favorite quotes by Mark Twain is, ""I...",Yiwet seg tnebdurin-inu timenyafin n Mark Twai...,CC-BY 2.0 (France) Attribution: tatoeba.org #6...
160878,If you talk to a man in a language he understa...,Mer ad as-temmeslayeḍ i umdan s tutlayt i ifeh...,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
160879,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160880,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...,CC-BY 2.0 (France) Attribution: tatoeba.org #7...

In [890]:
df.dtypes

Go.                                                                                object
Ṛuḥ.                                                                               object
CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)    object
dtype: object

In [891]:
# renaming columns
df.columns = ['english', 'amazigh', 'license']
df.head()

  english           amazigh                                            license
0     Hi.             Azul.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1     Hi.     Azul fell-ak.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2     Hi.     Azul fell-am.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3     Hi.   Azul fell-awen.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4     Hi.  Azul fell-awent.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...

In [892]:
# removing license column 
df = df.drop(columns=['license'])
df.head()

  english           amazigh
0     Hi.             Azul.
1     Hi.     Azul fell-ak.
2     Hi.     Azul fell-am.
3     Hi.   Azul fell-awen.
4     Hi.  Azul fell-awent.

In [893]:
# remove punctuation
df['english'] = df['english'].str.replace(r'[^\w\s]', '', regex=True)
df['amazigh'] = df['amazigh'].str.replace(r'[^\w\s]', '', regex=True)
df[10:]

,english,amazigh
10,Who,Anwa
11,Wow,Mmuqqel kan
12,Wow,Ayaa
13,Wow,ⵜⵉⵍⵉⵍⴰ
14,Wow,ⵜⵉⵍⵉⵍⴰ
...,...,...
160877,One of my favorite quotes by Mark Twain is Its...,Yiwet seg tnebdurininu timenyafin n Mark Twain...
160878,If you talk to a man in a language he understa...,Mer ad astemmeslayeḍ i umdan s tutlayt i ifehh...
160879,You cant view Flash content on an iPad However...,Ur tezmired ara ad twalid agbur n Flash deg us...
160880,You cant view Flash content on an iPad However...,Ur tezmired ara ad twalid agbur n Flash deg us...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...

In [894]:
# removing spaces
df['english'] = df['english'].str.strip()
df['amazigh'] = df['amazigh'].str.strip()
df[10:]

,english,amazigh
10,Who,Anwa
11,Wow,Mmuqqel kan
12,Wow,Ayaa
13,Wow,ⵜⵉⵍⵉⵍⴰ
14,Wow,ⵜⵉⵍⵉⵍⴰ
...,...,...
160877,One of my favorite quotes by Mark Twain is Its...,Yiwet seg tnebdurininu timenyafin n Mark Twain...
160878,If you talk to a man in a language he understa...,Mer ad astemmeslayeḍ i umdan s tutlayt i ifehh...
160879,You cant view Flash content on an iPad However...,Ur tezmired ara ad twalid agbur n Flash deg us...
160880,You cant view Flash content on an iPad However...,Ur tezmired ara ad twalid agbur n Flash deg us...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...

## Missing Data

In [895]:
# identifying missing data
df.isna()
# returns True for any missing values, in this case it doesn't have any

        english  amazigh
0         False    False
1         False    False
2         False    False
3         False    False
4         False    False
...         ...      ...
160877    False    False
160878    False    False
160879    False    False
160880    False    False
160881    False    False

[160882 rows x 2 columns]

In [896]:
df.isna().sum() 
# no missing values

english    0
amazigh    0
dtype: int64

In [897]:
df.dtypes

english    object
amazigh    object
dtype: object

## Duplicate Data

In [898]:
# checking for duplicate translation pairs
df.duplicated().sum()

np.int64(183)

In [899]:
df[df.duplicated(keep=False)]

,english,amazigh
7,Run,Azzel
9,Run,Azzel
13,Wow,ⵜⵉⵍⵉⵍⴰ
14,Wow,ⵜⵉⵍⵉⵍⴰ
22,Help,ⴰⵡⵙ
...,...,...
143649,Tom went to the library just to see Mary,Tom iṛuḥ ɣer temkarḍit akken kan ad iẓer Mary
155548,If Tom had a lot of money hed buy that for you,Lemmer yesɛi Tom aṭas n yidrimen tili ad awent...
155549,If Tom had a lot of money hed buy that for you,Lemmer yesɛi Tom aṭas n yidrimen tili ad awent...
155554,If Tom had a lot of money hed buy that for you,Lemmer ili Tom aṭas n yidrimen tili ad awentti...
155557,If Tom had a lot of money hed buy that for you,Lemmer ili Tom aṭas n yidrimen tili ad awentti...

In [900]:
# dropping duplicates & resetting index
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [901]:
df.duplicated().sum()

np.int64(0)

In [902]:
df['english'].duplicated().sum()

np.int64(76601)

In [903]:
df[df['english'].duplicated(keep=False)].sort_values('english')
# duplicates appear because of gender markers e.g., nne-k and nne-m suffixes in amazigh

,english,amazigh
87543,100 years is called a century,Meyya n yiseggasen ttininas lqern
87542,100 years is called a century,Tawinest n yiseggasen ttininas lqern
93674,A bad habit is easily acquired,Yir tanamit fessuset i ulmad
93673,A bad habit is easily acquired,Fessus ad yelmed yiwen yir tanamit
153865,A bicycle will rust if you leave it in the rain,Lemmer ad teǧǧed tasnasɣalt i unẓar ad tebṛec
...,...,...
2095,Youve won,Tellummẓeḍ
2094,Youve won,Tellummẓed
2093,Youve won,Trebḥemt
2090,Youve won,Trebḥed
2092,Youve won,Trebḥem

## Inconsistent Text & Typos Check

The data has a mix of Tifinagh script with Latin which is inconsistent, I will either try to convert all the Tifinagh into Latin, Latin to Tifinagh, or include both in separate columns.

In [904]:
df.describe()

            english              amazigh
count        160699               160699
unique        84098               149264
top     Go home now  Ur yettett ara waya
freq             56                   14

## Translation Variations

In [905]:
df.groupby("english")["amazigh"].nunique().sort_values(ascending=False).head(20)

english
Go home now                                 56
They hated you                              48
Do as you want                              45
Choose whichever you like                   42
You have lots of friends                    41
I want you to succeed                       40
They want you back                          40
You still have enough time                  38
Do you think this can work                  37
Do you think that this can work             37
You arent the only one Tom has cheated      36
Dont think Im going to let you do that      34
Have you finished writing the letter yet    33
Do they like you                            32
Youre not the only one who has a camera     32
They are pleased with your work             32
Tom just wants to be friends with you       32
Ive loved you since I first met you         32
They might be taller than you               32
Do you really want to win                   32
Name: amazigh, dtype: int64

## Current Findings

The corpus shows a high degree of translation variation, with many English sentences corresponding to multiple unique Amazigh translations. For example, “Go home now” has 56 unique Amazigh translations in the dataset.

Rather than treating these observations as duplicates, they may represent meaningful linguistic variation within the corpus.

Possible sources of variation include:

- Gender marking in Amazigh
- Singular and plural inflection
- Regional and dialectal variation across Amazigh varieties
- Lexical variation and alternative vocabulary choices

These patterns will be investigated further before additional cleaning or normalization decisions are made.

In [906]:
df[df["english"] == "Go home now"][["english", "amazigh"]]

          english                  amazigh
2406  Go home now      Ddu ɣer uxxam imira
2407  Go home now     Ddut ɣer uxxam imira
2408  Go home now     Ddum ɣer uxxam imira
2409  Go home now    Ddumt ɣer uxxam imira
2410  Go home now     Qqel ɣer uxxam imira
2411  Go home now    Qqlet ɣer uxxam imira
2412  Go home now    Qqlem ɣer uxxam imira
2413  Go home now   Qqlemt ɣer uxxam imira
2414  Go home now      Ṛuḥ ɣer uxxam imira
2415  Go home now    Ṛuḥet ɣer uxxam imira
2416  Go home now    Ṛuḥem ɣer uxxam imira
2417  Go home now   Ṛuḥemt ɣer uxxam imira
2418  Go home now       Ddu ɣer uxxam tura
2419  Go home now      Ddut ɣer uxxam tura
2420  Go home now      Ddum ɣer uxxam tura
2421  Go home now     Ddumt ɣer uxxam tura
2422  Go home now      Qqel ɣer uxxam tura
2423  Go home now     Qqlet ɣer uxxam tura
2424  Go home now     Qqlem ɣer uxxam tura
2425  Go home now    Qqlemt ɣer uxxam tura
2426  Go home now       Ṛuḥ ɣer uxxam tura
2427  Go home now     Ṛuḥet ɣer uxxam tura
2428  Go home now     Ṛuḥem ɣer uxxam tura
2429  Go home now    Ṛuḥemt ɣer uxxam tura
2430  Go home now     Uɣal ɣer uxxam imira
2431  Go home now   Uɣalet ɣer uxxam imira
2432  Go home now   Uɣalem ɣer uxxam imira
2433  Go home now  Uɣalemt ɣer uxxam imira
2434  Go home now      Uɣal ɣer uxxam tura
2435  Go home now    Uɣalet ɣer uxxam tura
2436  Go home now    Uɣalem ɣer uxxam tura
2437  Go home now   Uɣalemt ɣer uxxam tura
2438  Go home now        Ddu s axxam imira
2439  Go home now       Ddum s axxam imira
2440  Go home now       Ddut s axxam imira
2441  Go home now      Ddumt s axxam imira
2442  Go home now       Qqel s axxam imira
2443  Go home now      Qqlet s axxam imira
2444  Go home now      Qqlem s axxam imira
2445  Go home now     Qqlemt s axxam imira
2446  Go home now       Uɣal s axxam imira
2447  Go home now     Uɣalet s axxam imira
2448  Go home now     Uɣalem s axxam imira
2449  Go home now    Uɣalemt s axxam imira
2450  Go home now         Ddu s axxam tura
2451  Go home now        Ddut s axxam tura
2452  Go home now        Ddum s axxam tura
2453  Go home now       Ddumt s axxam tura
2454  Go home now        Uɣal s axxam tura
2455  Go home now      Uɣalet s axxam tura
2456  Go home now      Uɣalem s axxam tura
2457  Go home now     Uɣalemt s axxam tura
2458  Go home now        Qqel s axxam tura
2459  Go home now       Qqlet s axxam tura
2460  Go home now       Qqlem s axxam tura
2461  Go home now      Qqlemt s axxam tura

## Tifinagh Script Column

In [907]:
# creating a Tifinagh script column
df['tifinagh'] = pd.NA
df.head()

  english         amazigh tifinagh
0      Hi            Azul     <NA>
1      Hi     Azul fellak     <NA>
2      Hi     Azul fellam     <NA>
3      Hi   Azul fellawen     <NA>
4      Hi  Azul fellawent     <NA>

In [908]:
# detect tifinagh characters: unicode U+2D30–U+2D7F
tifinagh_mask = df['amazigh'].str.contains(r'[\u2D30-\u2D7F]',regex=True,na=False)

In [909]:
# copy tifinagh entries
df.loc[tifinagh_mask, 'tifinagh'] = df.loc[tifinagh_mask, 'amazigh']

# remove tifinagh entries from amazigh
df.loc[tifinagh_mask, 'amazigh'] = pd.NA

# classify writing system
df['script'] = 'Latin'
df.loc[tifinagh_mask, 'script'] = 'Tifinagh'

df[:15]

   english         amazigh tifinagh    script
0       Hi            Azul     <NA>     Latin
1       Hi     Azul fellak     <NA>     Latin
2       Hi     Azul fellam     <NA>     Latin
3       Hi   Azul fellawen     <NA>     Latin
4       Hi  Azul fellawent     <NA>     Latin
5       Hi            <NA>     ⴰⵣⵓⵍ  Tifinagh
6       Hi            azul     <NA>     Latin
7      Run           Azzel     <NA>     Latin
8      Run            <NA>     ⴰⵣⵣⵍ  Tifinagh
9      Who            Anwa     <NA>     Latin
10     Wow     Mmuqqel kan     <NA>     Latin
11     Wow            Ayaa     <NA>     Latin
12     Wow            <NA>   ⵜⵉⵍⵉⵍⴰ  Tifinagh
13    Fire           Times     <NA>     Latin
14    Fire         Qerrset     <NA>     Latin

In [910]:
# check whether the amazigh output is in Latin or Tifinagh 
df['script'].value_counts()

script
Latin       160647
Tifinagh        52
Name: count, dtype: int64

In [911]:
df[['english', 'tifinagh']].dropna()

,english,tifinagh
5,Hi,ⴰⵣⵓⵍ
8,Run,ⴰⵣⵣⵍ
12,Wow,ⵜⵉⵍⵉⵍⴰ
18,Fire,ⵜⴰⴽⴰⵜ
20,Help,ⴰⵡⵙ
21,Jump,ⵏⴹⴻⵔ
22,Jump,ⵏⴹⴻⵕ
25,Stop,ⴱⵉⴷⴷ
27,Wait,ⵇⵇⴻⵍ
33,Hello,ⴰⵣⵓⵍ
43,I try,ⴰⵔ ⵜⵜⴰⵔⴻⵎⵖ
55,Cheers,ⵙ ⵜⴷⵓⵙⵉ ⵏⵏⴻⴽ
84,Really,ⵜⵉⴷⴻⵜ
87,Thanks,ⵜⴰⵏⴻⵎⵎⵉⵔⵜ
96,Why me,ⵎⴰⵅ ⵏⵉⴽ
102,Awesome,ⵓⵔ ⵉⵍⵍⵉ ⵎⴰⵜ ⵢⵓⴼⵏ
103,Awesome,ⵉⵛⵡⴰ ⴱⴰⵀⵔⴰ
169,Goodbye,ⴰⵔ ⵜⵓⴼⴰⵜ
272,Welcome,ⴱⴻⵔⵔⴽ
273,Welcome,ⴰⵏⵚⵓⴼ ⴱⴻⵔⵔⴽ
515,Nonsense,ⴰⵡⴰⵍ ⴳⴰⵔ ⵜⴰⴹⴼⵉ
556,Terrific,ⵉⵛⵡⴰ
700,Come here,ⴰⵛⴽⵉⴷ ⵙ ⵖⵉⴷ
715,Fantastic,ⵉⵛⵡⴰ ⴱⴰⵀⵔⴰ
725,Forget it,ⵜⵜⵓ ⵜ
736,Goodnight,ⵜⵉⵎⴻⵏⵙⵉⵡⵉⵏ
999,Take care,ⵜⵀⴻⵍⵍⴰ
1100,Try again,ⴰⵔⴻⵎ ⴷⴰⵖ
1142,Wonderful,ⵉⴼⵓⵍⴽⵉ ⴱⴰⵀⵔⴰ
1309,Definitely,ⵖⴻⵎⴽⴰⵏ ⵏⵉⵜ
1354,Forgive us,ⵙⵙⵓⵔⴼ ⴰⵖ
2835,Money talks,ⵉⵇⴰⵔⵉⴹⵏ ⴰⵢ ⵙⴰⵡⴰⵍⵏ
3342,Walk slowly,ⵜⴷⴷⴰ ⵙ ⵉⵎⵉⴽ
3628,Anything new,ⵉⵙ ⵉⵍⵍⴰ ⴽⵔⴰ ⵏ ⵓⵎⴰⵢⵏⵓ
3815,Can Tom sing,ⵉⵙⵙⵏ ⵟⵓⵎ ⴰⴷ ⵢⵛⵏⵓ
3856,Come quickly,ⴰⵛⴽⴷ ⵙ ⵣⵣⴻⵔⴱ
4649,Sweet dreams,ⵜⵉⵡⴰⵔⴳⵉⵡⵉⵏ ⵉⵎⵎⵉⵎⵏ
5101,Unbelievable,ⵓⵔ ⵔⴰ ⵙⴻⵔⵙ ⵜⴼⴻⵍⵙⵜ
8791,Do you like it,ⵜⵔⵉ ⵜ
17129,Listen carefully,ⵙⴼⴻⵍⴳ ⵎⵣⵢⴰⵏ
20293,Everybody laughed,ⴰⵔ ⵉⴹⵚⵚⴰ ⴽⵔⴰⵢⴳⴰⵜ ⵢⴰⵏ
30449,I have lost the key,ⵜⵕⵓⵃⵉⵢⵉ ⵜⵙⴰⵔⴰⵓⵜ
37518,Tom isnt responding,ⵓⵔ ⴷⴰ ⵉⵜⵜⵔⴰ ⵟⵓⵎ
53696,The bulb has burned out,ⵜⴻⵜⵜⵡⴰⵊⴷⴰⵔ ⵜⵙⴰⴼⵓⵜ
64229,How many cars do you have,ⴰⵛⵃⴰⵍ ⵜⴻⵙⵄⵉⴹ ⴷ ⵜⵉⴽⴻⵕⵕⵓⵙⵉⵏ
95638,I want to have a word with you,ⵙⵄⵉⵖ ⵉⵎⴻⵙⵍⴰⵢⴻⵏ ⴰⵔⴰ ⴽ ⴷ ⵉⵏⵉⵖ
97144,Tom dropped Mary off at school,ⵜⵓⵎ ⵢⴻⵙⵙⴻⵔⵙ ⵎⴰⵔⵉ ⴷⴻⴳ ⵓⵖⴻⵔⴱⴰⵣ
122397,Tom didnt stay in Boston very long,ⵓⵔ ⵏⵏ ⴱⴰⵀⵔⴰ ⵉⵎⴰⵟⵉⵍ ⵜⵓⵎ ⴳ ⴱⵓⵙⵜⵏ
125494,Ive managed to persuade Tom to come,ⵙⵙⴰⵡⴹⴻⵖ ⴰⴷ ⵙⵇⴻⵏⵄⴻⵖ ⵜⵓⵎ ⴰⴷ ⴷⵢⴰⵙ
135349,He doesnt know anything about politics,Ur issin awed ḥaḥ g tsertit ⵓⵔ ⵉⵙⵙⵉⵏ ⴰⵡⴷ ⵃⴰⵃ ⴳ...
139283,Ill go to the library with you tomorrow,ⴰⴷ ⴷⴷⵓⵖ ⴰⴽⴷ ⵉⴽ ⵖⵔ ⵜⵙⴷⵍⵉⵙⵜ ⴰⵙⵙⴽⴰ
139519,Most people write about their daily life,ⴰⵟⴰⵙ ⵏ ⵎⴻⴷⴷⴻⵏ ⴰⵢ ⵢⴻⵜⵜⴰⵔⵓⵏ ⵖⴻⴼ ⵜⵓⴷⴻⵔⵜⵏⵙⴻⵏ ⵏ ⵢⴰⵍ...

row 135349 has a mix of tifinagh and latin concatenated together -> will separate the two

In [912]:
df.loc[135349]

english                He doesnt know anything about politics
amazigh                                                  <NA>
tifinagh    Ur issin awed ḥaḥ g tsertit ⵓⵔ ⵉⵙⵙⵉⵏ ⴰⵡⴷ ⵃⴰⵃ ⴳ...
script                                               Tifinagh
Name: 135349, dtype: object

In [913]:
df.loc[135349, 'amazigh'] = 'Ur issin awed ḥaḥ g tsertit'
df.loc[135349, 'tifinagh'] = 'ⵓⵔ ⵉⵙⵙⵉⵏ ⴰⵡⴷ ⵃⴰⵃ ⴳ ⵜⵙⴻⵔⵜⵉⵜ'

In [914]:
df.loc[135349]

english     He doesnt know anything about politics
amazigh                Ur issin awed ḥaḥ g tsertit
tifinagh                ⵓⵔ ⵉⵙⵙⵉⵏ ⴰⵡⴷ ⵃⴰⵃ ⴳ ⵜⵙⴻⵔⵜⵉⵜ
script                                    Tifinagh
Name: 135349, dtype: object

In [915]:
df[['english', 'amazigh', 'tifinagh']].dropna()

,english,amazigh,tifinagh
135349,He doesnt know anything about politics,Ur issin awed ḥaḥ g tsertit,ⵓⵔ ⵉⵙⵙⵉⵏ ⴰⵡⴷ ⵃⴰⵃ ⴳ ⵜⵙⴻⵔⵜⵉⵜ

### Findings
- Majority of amazigh data is written in Latin, Tifinagh is scarce 
- Solution: either manually add Tifinagh equivalent or focus only on Latin version