In [182]:
import kagglehub
import pandas as pd

In [183]:
path = kagglehub.dataset_download('jasminemohamed2545/berber-english-160k-parallel-sentences-for-nlp')
print(path)

C:\Users\lassa\.cache\kagglehub\datasets\jasminemohamed2545\berber-english-160k-parallel-sentences-for-nlp\versions\1

In [184]:
df = pd.read_table('ber.txt')
df

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
0,Hi.,Azul.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1,Hi.,Azul fell-ak.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2,Hi.,Azul fell-am.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3,Hi.,Azul fell-awen.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Azul fell-awent.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
...,...,...,...
160877,"One of my favorite quotes by Mark Twain is, ""I...",Yiwet seg tnebdurin-inu timenyafin n Mark Twai...,CC-BY 2.0 (France) Attribution: tatoeba.org #6...
160878,If you talk to a man in a language he understa...,Mer ad as-temmeslayeḍ i umdan s tutlayt i ifeh...,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
160879,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160880,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...,CC-BY 2.0 (France) Attribution: tatoeba.org #7...

In [185]:
df.dtypes

Go.                                                                                object
Ṛuḥ.                                                                               object
CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)    object
dtype: object

In [186]:
# renaming columns
df.columns = ['english', 'amazigh', 'license']
df.head()

  english           amazigh                                            license
0     Hi.             Azul.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1     Hi.     Azul fell-ak.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2     Hi.     Azul fell-am.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3     Hi.   Azul fell-awen.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4     Hi.  Azul fell-awent.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...

In [187]:
# removing license column 
df = df.drop(columns=['license'])
df.head()

  english           amazigh
0     Hi.             Azul.
1     Hi.     Azul fell-ak.
2     Hi.     Azul fell-am.
3     Hi.   Azul fell-awen.
4     Hi.  Azul fell-awent.

In [188]:
# removing periods 
df['english'] = df['english'].str.replace('.', '', regex=False)
df['amazigh'] = df['amazigh'].str.replace('.', '', regex=False)
df.head()

  english          amazigh
0      Hi             Azul
1      Hi     Azul fell-ak
2      Hi     Azul fell-am
3      Hi   Azul fell-awen
4      Hi  Azul fell-awent

## Missing Data

In [189]:
# identifying missing data
df.isna()
# returns True for any missing values, in this case it doesn't have any

        english  amazigh
0         False    False
1         False    False
2         False    False
3         False    False
4         False    False
...         ...      ...
160877    False    False
160878    False    False
160879    False    False
160880    False    False
160881    False    False

[160882 rows x 2 columns]

In [190]:
df.isna().sum() 
# no missing values

english    0
amazigh    0
dtype: int64

In [191]:
df.dtypes

english    object
amazigh    object
dtype: object

## Duplicate Data

In [192]:
# checking for duplicate translation pairs
df.duplicated().sum()

np.int64(5)

In [193]:
df[df.duplicated(keep=False)]
# these duplicates add no new value

                                   english                         amazigh
173                               Get out!                           Ffeɣ!
174                               Get out!                           Ffeɣ!
3048                           They agreed                       Msefhamen
3052                           They agreed                       Msefhamen
7247                         They're empty                       D ilmawen
7248                         They're empty                       D ilmawen
34730                Do you speak English?           Tessawaled tanglizit?
34731                Do you speak English?           Tessawaled tanglizit?
110964  Do you study any foreign language?  Teqqareḍ kra n yiles abeṛṛani?
110965  Do you study any foreign language?  Teqqareḍ kra n yiles abeṛṛani?

In [194]:
# dropping duplicates & resetting index
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [195]:
df.duplicated().sum()

np.int64(0)

In [196]:
df["english"].duplicated().sum()

np.int64(76710)

In [197]:
df[df["english"].duplicated(keep=False)].sort_values("english")
# duplicates appear because of gender markers e.g., nne-k and nne-m suffixes in amazigh

,english,amazigh
87710,100 years is called a century,Tawinest n yiseggasen ttinin-as “lqern”
87711,100 years is called a century,Meyya n yiseggasen ttinin-as “lqern”
93843,A bad habit is easily acquired,Fessus ad yelmed yiwen yir tanamit
93844,A bad habit is easily acquired,Yir tanamit fessuset i ulmad
154042,A bicycle will rust if you leave it in the rain,"Tasnasɣalt, lemmer ad tt-teǧǧed i unẓar, ad te..."
...,...,...
62835,Your writing is horrible,Ssexlaɛent tira-nwent
11663,Yours is worse,Winna-nnek diri-t ugar
11664,Yours is worse,Winna-nnem diri-t ugar
19827,Yours was better,D winna-nnem ay yelhan
19826,Yours was better,D winna-nnek ay yelhan

## Inconsistent Text & Typos Check

The data has a mix of Tifinagh script with Latin which is inconsistent, I will either try to convert all the Tifinagh into Latin, Latin to Tifinagh, or include both in separate columns.

In [198]:
df.describe()

            english              amazigh
count        160877               160877
unique        84167               150049
top     Go home now  Ur yettett ara waya
freq             56                   14

## Translation Variations

In [199]:
df.groupby("english")["amazigh"].nunique().sort_values(ascending=False).head(20)

english
Go home now                                  56
They hated you                               48
Do as you want                               45
Choose whichever you like                    42
You have lots of friends                     41
I want you to succeed                        40
They want you back                           40
You still have enough time                   38
Do you think that this can work?             37
Do you think this can work?                  37
You aren't the only one Tom has cheated      36
Don't think I'm going to let you do that     34
Have you finished writing the letter yet?    33
They are pleased with your work              32
They want to see you                         32
I've loved you since I first met you         32
Do you really want to win?                   32
You're not the only one who has a camera     32
You're prepared                              32
They might be taller than you                32
Name: amazigh, dtype: int64

## Current Findings

The corpus shows a high degree of translation variation, with many English sentences corresponding to multiple unique Amazigh translations. For example, “Go home now” has 56 unique Amazigh translations in the dataset.

Rather than treating these observations as duplicates, they may represent meaningful linguistic variation within the corpus.

Possible sources of variation include:

- Gender marking in Amazigh
- Singular and plural inflection
- Regional and dialectal variation across Amazigh varieties
- Lexical variation and alternative vocabulary choices

These patterns will be investigated further before additional cleaning or normalization decisions are made.

In [200]:
df[df["english"] == "Go home now"][["english", "amazigh"]]

          english                   amazigh
2456  Go home now      Ddu ɣer uxxam imir-a
2457  Go home now     Ddut ɣer uxxam imir-a
2458  Go home now     Ddum ɣer uxxam imir-a
2459  Go home now    Ddumt ɣer uxxam imir-a
2460  Go home now     Qqel ɣer uxxam imir-a
2461  Go home now    Qqlet ɣer uxxam imir-a
2462  Go home now    Qqlem ɣer uxxam imir-a
2463  Go home now   Qqlemt ɣer uxxam imir-a
2464  Go home now      Ṛuḥ ɣer uxxam imir-a
2465  Go home now    Ṛuḥet ɣer uxxam imir-a
2466  Go home now    Ṛuḥem ɣer uxxam imir-a
2467  Go home now   Ṛuḥemt ɣer uxxam imir-a
2468  Go home now       Ddu ɣer uxxam tur-a
2469  Go home now      Ddut ɣer uxxam tur-a
2470  Go home now      Ddum ɣer uxxam tur-a
2471  Go home now     Ddumt ɣer uxxam tur-a
2472  Go home now      Qqel ɣer uxxam tur-a
2473  Go home now     Qqlet ɣer uxxam tur-a
2474  Go home now     Qqlem ɣer uxxam tur-a
2475  Go home now    Qqlemt ɣer uxxam tur-a
2476  Go home now       Ṛuḥ ɣer uxxam tur-a
2477  Go home now     Ṛuḥet ɣer uxxam tur-a
2478  Go home now     Ṛuḥem ɣer uxxam tur-a
2479  Go home now    Ṛuḥemt ɣer uxxam tur-a
2480  Go home now     Uɣal ɣer uxxam imir-a
2481  Go home now   Uɣalet ɣer uxxam imir-a
2482  Go home now   Uɣalem ɣer uxxam imir-a
2483  Go home now  Uɣalemt ɣer uxxam imir-a
2484  Go home now      Uɣal ɣer uxxam tur-a
2485  Go home now    Uɣalet ɣer uxxam tur-a
2486  Go home now    Uɣalem ɣer uxxam tur-a
2487  Go home now   Uɣalemt ɣer uxxam tur-a
2488  Go home now        Ddu s axxam imir-a
2489  Go home now       Ddum s axxam imir-a
2490  Go home now       Ddut s axxam imir-a
2491  Go home now      Ddumt s axxam imir-a
2492  Go home now       Qqel s axxam imir-a
2493  Go home now      Qqlet s axxam imir-a
2494  Go home now      Qqlem s axxam imir-a
2495  Go home now     Qqlemt s axxam imir-a
2496  Go home now       Uɣal s axxam imir-a
2497  Go home now     Uɣalet s axxam imir-a
2498  Go home now     Uɣalem s axxam imir-a
2499  Go home now    Uɣalemt s axxam imir-a
2500  Go home now         Ddu s axxam tur-a
2501  Go home now        Ddut s axxam tur-a
2502  Go home now        Ddum s axxam tur-a
2503  Go home now       Ddumt s axxam tur-a
2504  Go home now        Uɣal s axxam tur-a
2505  Go home now      Uɣalet s axxam tur-a
2506  Go home now      Uɣalem s axxam tur-a
2507  Go home now     Uɣalemt s axxam tur-a
2508  Go home now        Qqel s axxam tur-a
2509  Go home now       Qqlet s axxam tur-a
2510  Go home now       Qqlem s axxam tur-a
2511  Go home now      Qqlemt s axxam tur-a

## Tifinagh Script Column

In [201]:
df['Tifinagh'] = pd.NA
df.head()

  english          amazigh Tifinagh
0      Hi             Azul     <NA>
1      Hi     Azul fell-ak     <NA>
2      Hi     Azul fell-am     <NA>
3      Hi   Azul fell-awen     <NA>
4      Hi  Azul fell-awent     <NA>

In [202]:
# detect Tifinagh characters : Unicode 2D30 - 2D7F
tifinagh = df['amazigh'].str.contains(r'[\u2D30-\u2D7F]', regex=True)

In [203]:
df.loc[tifinagh, 'Tifinagh'] = df.loc[tifinagh, 'amazigh']
df[:10]

  english          amazigh Tifinagh
0      Hi             Azul     <NA>
1      Hi     Azul fell-ak     <NA>
2      Hi     Azul fell-am     <NA>
3      Hi   Azul fell-awen     <NA>
4      Hi  Azul fell-awent     <NA>
5      Hi             ⴰⵣⵓⵍ     ⴰⵣⵓⵍ
6      Hi             azul     <NA>
7    Run!           Azzel!     <NA>
8    Run!             ⴰⵣⵣⵍ     ⴰⵣⵣⵍ
9     Run            Azzel     <NA>

In [ ]:
# removing Tifinagh from amazigh section (will display NA if missing)
df.loc[tifinagh, 'amazigh'] = pd.NA
df[:10]

  english          amazigh Tifinagh
0      Hi             Azul     <NA>
1      Hi     Azul fell-ak     <NA>
2      Hi     Azul fell-am     <NA>
3      Hi   Azul fell-awen     <NA>
4      Hi  Azul fell-awent     <NA>
5      Hi             <NA>     ⴰⵣⵓⵍ
6      Hi             azul     <NA>
7    Run!           Azzel!     <NA>
8    Run!             <NA>     ⴰⵣⵣⵍ
9     Run            Azzel     <NA>